openapi: 3.0.3
info:
  title: OpenAPI schema for Origin CA template .
components:
  schemas:
    variables:
      type: object
      properties:
        manifests_urls:
          title: Manifests Urls
          type: array
          description: URLs list from the raw manifests
          default:
          - https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/refs/heads/trunk/deploy/crds/cert-manager.k8s.cloudflare.com_originissuers.yaml
          - https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/refs/heads/trunk/deploy/crds/cert-manager.k8s.cloudflare.com_clusteroriginissuers.yaml
          items:
            type: string
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 1
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where resources will be created.
          default: origin-ca
          x-walrus-ui:
            group: Basic
            order: 2
        key:
          title: Key
          type: string
          description: Secret key for cloudflare
          default: ""
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 3
        helm_release_name:
          title: Helm Release Name
          type: string
          description: The name of the Helm release.
          default: origin-ca-issuer
          x-walrus-ui:
            group: Basic
            order: 4
        helm_chart_version:
          title: Helm Chart Version
          type: string
          description: The version of the Helm chart.
          default: 0.5.5
          x-walrus-ui:
            group: Basic
            order: 5
      x-walrus-ui:
        groupOrder:
        - Basic
