openapi: 3.0.3
info:
  title: OpenAPI schema for Origin CA template .
components:
  schemas:
    variables:
      type: object
      properties:
        manifests_urls:
          title: Manifests Urls
          type: array
          description: URLs list from the raw manifests
          default:
          - https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/refs/heads/trunk/deploy/crds/cert-manager.k8s.cloudflare.com_originissuers.yaml
          - https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/refs/heads/trunk/deploy/crds/cert-manager.k8s.cloudflare.com_clusteroriginissuers.yaml
          items:
            type: string
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 1
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where resources will be created.
          default: origin-ca
          x-walrus-ui:
            group: Basic
            order: 2
        image_version:
          title: Image Version
          type: string
          description: origin-ca-issuer version.
          default: cloudflare/origin-ca-issuer:v0.9.0
          x-walrus-ui:
            group: Basic
            order: 3
        key:
          title: Key
          type: string
          description: Secret key for cloudflare
          default: ""
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 4
        resources:
          title: Resources
          type: object
          description: Resource limits and requests for the Origin-CA Helm release.
          default:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 1000m
              memory: 512Mi
          additionalProperties:
            additionalProperties:
              type: string
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 5
        hpa_config:
          title: Hpa Config
          type: object
          description: Configuration for the HPA targeting OriginCA Deployment
          default:
            max_replicas: 3
            min_replicas: 1
            target_cpu_utilization: 80
            target_memory_utilization: 80
          required:
          - max_replicas
          - min_replicas
          - target_cpu_utilization
          - target_memory_utilization
          properties:
            max_replicas:
              title: Max Replicas
              type: number
              x-walrus-ui:
                order: 2
            min_replicas:
              title: Min Replicas
              type: number
              x-walrus-ui:
                order: 1
            target_cpu_utilization:
              title: Target Cpu Utilization
              type: number
              x-walrus-ui:
                order: 3
            target_memory_utilization:
              title: Target Memory Utilization
              type: number
              x-walrus-ui:
                order: 4
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 6
      x-walrus-ui:
        groupOrder:
        - Basic
