openapi: 3.0.3
info:
  title: OpenAPI schema for Origin CA template .
components:
  schemas:
    variables:
      type: object
      properties:
        # manifests_urls:
        #   title: Manifests Urls
        #   type: array
        #   description: URLs list from the raw manifests
        #   default:
        #   - https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/refs/heads/trunk/deploy/crds/cert-manager.k8s.cloudflare.com_originissuers.yaml
        #   - https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/refs/heads/trunk/deploy/crds/cert-manager.k8s.cloudflare.com_clusteroriginissuers.yaml
        #   items:
        #     type: string
        #   x-walrus-ui:
        #     colSpan: 12
        #     group: Basic
        #     order: 1
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where resources will be created.
          default: origin-ca
          x-walrus-ui:
            group: Basic
            order: 1
        image_version:
          title: Image Version
          type: string
          description: origin-ca-issuer version.
          default: cloudflare/origin-ca-issuer:v0.9.0
          x-walrus-ui:
            group: Basic
            order: 2
        key:
          title: Key
          type: string
          description: secret key for cloudflare
          default: ""
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 3
      x-walrus-ui:
        groupOrder:
        - Basic
