openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      properties:
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where resources will be created.
          default: origin-ca
          x-walrus-ui:
            group: Basic
            order: 1
        image_version:
          title: Image Version
          type: string
          description: origin-ca-issuer version.
          default: cloudflare/origin-ca-issuer:v0.9.0
          x-walrus-ui:
            group: Basic
            order: 2
        key:
          title: Key
          type: string
          description: secret key for cloudflare
          default: ""
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 3
      x-walrus-ui:
        groupOrder:
        - Basic
